# Generated by Django 4.2.4 on 2023-08-15 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CapturedImage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='captured_images/')),
                ('capture_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
