# Generated by Django 4.2.4 on 2023-08-15 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_capturedimage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CapturedImage',
        ),
    ]
