# Generated by Django 4.2.4 on 2023-08-15 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_captured_delete_capturedimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='FaceDB',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('record_date', models.DateField(auto_now_add=True)),
                ('image', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.DeleteModel(
            name='Captured',
        ),
        migrations.DeleteModel(
            name='FaceRecognition',
        ),
    ]
