# Generated by Django 4.2.4 on 2023-09-03 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_facedb_delete_captured_delete_facerecognition'),
    ]

    operations = [
        migrations.CreateModel(
            name='nets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
            ],
        ),
    ]
